version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    groups:
      action-version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
      action-security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
